security:
    endpoints:
        public:
            - path: /api/v1/users
              method: POST
        admin: 
            - path: /api/v1/users/**
              methods: [GET, POST, PUT, DELETE]
            - path: /api/v1/tasks/**
              methods: [GET, POST, PUT, DELETE]
            - path: /api/v1/tasks/category/**
              methods: [GET, POST, PUT, DELETE]
        user: 
            - path: /api/v1/tasks/**
              methods: [GET, POST, PUT, DELETE]
            - path: /api/v1/tasks/category/**
              methods: [GET, POST, PUT, DELETE]